### ISSUE TITLE
Black screen after building project

### ISSUE THREAD

**Issue by Benzilla** [charlesveasey/UnityDomemaster#2]
Hi,

I'm having an issue where I'm able to see the warped/fish eye view when previewing my game in the unity editor, but once I build and run the project I'm presented with a black screen.

In editor: https://gyazo.com/638c70f4e7cba1cb062d039b2da15bac
Built version: https://gyazo.com/a6018a1d6d23f99c64f0d804b2b79101

I have tested this with a completely blank, fresh project. I drag the DomeCamera Prefab and DomeMaster Prefab into my scene as stated. I am running Unity 5.1 on a laptop running Windows 10.

Are there any settings in Unity that could be causing this?

**Comment by charlesveasey** [comment]
Thanks for pointing this out. There was some oddity in the Editor macro. It should work now.
