### ISSUE TITLE
offset

### ISSUE THREAD

**Issue by fooldome** [charlesveasey/UnityDomemaster#3]
Hi,

Great work. The character setups are very easy to offset for truncated domes, as laid out by Paul Bourke by changing the size and position of the fisheye camera. Is there anyway to do this with the shader example? - most of my attempts to manipulate the v2f to offset or enlarge circle just break it.

Best wishes
Luke

**Comment by charlesveasey** [comment]
Hi Luke, 

what do you mean truncated domes? can you link a picture?

**Comment by fooldome** [comment]
its a forward facing dome where the back part is actually removed. So the domemaster is often bigger and offset to not include the back camera but still fills the screen. 
Like this: [http://wiki.blender.org/uploads/1/1e/Dev-GameEngine-Dome-Rear-Truncated.jpg](url)

**Comment by charlesveasey** [comment]
You can either modify the shader or render the fisheye camera to a texture, place it on a plane, then use an orthographic camera for final output. The second method allow you to make adjustments using Unity editor controls. 
![truncated-example](https://cloud.githubusercontent.com/assets/3144590/13204696/bfeaf0ac-d893-11e5-9039-2b0a7435270b.jpg)

**Comment by fooldome** [comment]
Render to texture method works well, thanks for help.
