### ISSUE TITLE
Recommended sizes of render textures

### ISSUE THREAD

**Issue by jvolker** [charlesveasey/UnityDomemaster#5]
First of all, thanks for sharing this! 

The default sizes are currently 1024 x 1024 pixels per RenderTexture. But this might not be enough for higher resolution setups. 
My question is, what are the recommended sizes of the render textures? Is there a way to calculate this depending on the desired final resolution?

In particular, I'm interested in the recommended sizes for a final resolution of 2K and 4K with the 4 camera setup. 

Cheers!

**Comment by charlesveasey** [comment]
Hello,

I don't have any recommended texture sizes as it's based on your demands
and GPU. To roughly calculate the overall domemaster resolution, add the
resolution of the render textures across the diameter of the circle. So 1K
textures with either the 4 or 5 camera set up will give you an overall 2k
domemaster. The five camera rig providing a wider field of view.

I hope this helps!

Best,
Charles
